# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0003_auto_20160503_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='value',
            new_name='_fixed_value',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='value_currency',
            new_name='_fixed_value_currency',
        ),
    ]
