# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 20:59
from __future__ import unicode_literals

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0004_auto_20160505_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='_fixed_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='USD', max_digits=10, null=True),
        ),
    ]
