# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0005_auto_20160505_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='repeat',
            field=models.IntegerField(default=0),
        ),
    ]
