# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0006_expense_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='repeat',
        ),
        migrations.AddField(
            model_name='expense',
            name='occurrence',
            field=models.IntegerField(default=1),
        ),
    ]
