# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 23:05
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0008_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='_fixed_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='_fixed_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=10, null=True),
        ),
    ]
