# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0010_auto_20160506_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
