# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0011_quotation_is_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_required',
            field=models.BooleanField(default=True),
        ),
    ]
