# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 03:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0015_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashinput',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 8, 3, 24, 58, 226032, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
