# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_fund_partners'),
        ('cash_flow', '0018_auto_20160508_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='fund',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fund.Fund'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='fund',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='fund.Fund'),
            preserve_default=False,
        ),
    ]
