# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_fund_partners'),
        ('cash_flow', '0020_auto_20160508_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fund',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='fund.Fund'),
            preserve_default=False,
        ),
    ]
