# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0021_account_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
