# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0023_cashinput_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashinput',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='cash_flow.InputCategory'),
        ),
    ]
