# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0024_auto_20160508_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashinput',
            name='category',
        ),
        migrations.AddField(
            model_name='cashinput',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='inputs', to='cash_flow.InputCategory'),
        ),
    ]
