# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='partners',
            field=models.ManyToManyField(related_name='funds', to=settings.AUTH_USER_MODEL),
        ),
    ]
